apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 781693258858.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: 2f8187e97c531e7869c4c2a7b18442dc9bdbfe7b
